--
-- Data
--

INSERT INTO ACTIVITIES(NAME,URI,PARAMS,INS_DATE) VALUES('demo','mock','{"greeting":"hello"}',SYSTIMESTAMP);

INSERT INTO JOBS(ACTIVITY,EXPRESSION,INS_DATE) VALUES('demo','1000 5000',SYSTIMESTAMP);

COMMIT;