--
-- Tables of schema WCRON
--

CREATE TABLE ACTIVITIES(NAME VARCHAR(50) NOT NULL,URI VARCHAR(100) NOT NULL,PARAMS VARCHAR(255),INS_DATE TIMESTAMP NOT NULL,UPD_DATE TIMESTAMP,CONSTRAINT PK_ACTIVITIES PRIMARY KEY (NAME));

CREATE TABLE JOBS(ID BIGINT AUTO_INCREMENT,ACTIVITY VARCHAR(50) NOT NULL,PARAMS VARCHAR(255),EXPRESSION  VARCHAR(50) NOT NULL,LAST_RESULT VARCHAR(255),LAST_ERROR VARCHAR(255),ELAPSED INT NOT NULL DEFAULT 0,INS_DATE TIMESTAMP NOT NULL,UPD_DATE TIMESTAMP,CONSTRAINT PK_JOBS PRIMARY KEY (ID));

